FROM nginx

# Copy the custom NGINX configuration if needed
COPY nginx.conf /etc/nginx/

# Copy the HTML and CSS files to the correct default NGINX directory
COPY index.html /usr/share/nginx/html
COPY affirmationicon.jpg /usr/share/nginx/html